// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package eventrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// NotifierClient is the client API for Notifier service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotifierClient interface {
	// Client subscribes to receive notifications
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (Notifier_SubscribeClient, error)
}

type notifierClient struct {
	cc grpc.ClientConnInterface
}

func NewNotifierClient(cc grpc.ClientConnInterface) NotifierClient {
	return &notifierClient{cc}
}

func (c *notifierClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (Notifier_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Notifier_serviceDesc.Streams[0], "/protobuf.Notifier/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &notifierSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Notifier_SubscribeClient interface {
	Recv() (*Notification, error)
	grpc.ClientStream
}

type notifierSubscribeClient struct {
	grpc.ClientStream
}

func (x *notifierSubscribeClient) Recv() (*Notification, error) {
	m := new(Notification)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NotifierServer is the server API for Notifier service.
// All implementations must embed UnimplementedNotifierServer
// for forward compatibility
type NotifierServer interface {
	// Client subscribes to receive notifications
	Subscribe(*SubscribeRequest, Notifier_SubscribeServer) error
	mustEmbedUnimplementedNotifierServer()
}

// UnimplementedNotifierServer must be embedded to have forward compatible implementations.
type UnimplementedNotifierServer struct {
}

func (UnimplementedNotifierServer) Subscribe(*SubscribeRequest, Notifier_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedNotifierServer) mustEmbedUnimplementedNotifierServer() {}

// UnsafeNotifierServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotifierServer will
// result in compilation errors.
type UnsafeNotifierServer interface {
	mustEmbedUnimplementedNotifierServer()
}

func RegisterNotifierServer(s *grpc.Server, srv NotifierServer) {
	s.RegisterService(&_Notifier_serviceDesc, srv)
}

func _Notifier_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NotifierServer).Subscribe(m, &notifierSubscribeServer{stream})
}

type Notifier_SubscribeServer interface {
	Send(*Notification) error
	grpc.ServerStream
}

type notifierSubscribeServer struct {
	grpc.ServerStream
}

func (x *notifierSubscribeServer) Send(m *Notification) error {
	return x.ServerStream.SendMsg(m)
}

var _Notifier_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.Notifier",
	HandlerType: (*NotifierServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _Notifier_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protobuf/eventrpc/eventrpc.proto",
}
